### ISSUE TITLE
does not recognise English

### ISSUE THREAD

**Issue by PradeepOjha** [barrust/pyspellchecker#6]
from spellchecker import SpellChecker

spell = SpellChecker()

# find those words that may be misspelled
misspelled = spell.unknown(['something', 'is', 'hapenning', 'here'])

Result -----

  File "C:\Users\xyz\Miniconda2\lib\site-packages\spellchecker\spellchecker.py", line 35, in __init__
    raise ValueError(msg)

ValueError: The provided dictionary language (en) does not exist!

**Comment by barrust** [comment]
Ugh, thank you for pointing this out! My latest build did not include the dictionaries. I will have a build out later today with the fix.

**Comment by barrust** [comment]
Please use version 0.1.2 as it should now be working as expected. Sorry for the messed up pypi package. 

`pip install --upgrade pyspellchecker`

**Comment by PradeepOjha** [comment]
Successfully  upgraded spellchecler. Attached is screen shot.

![spellcheckerror](https://user-images.githubusercontent.com/11005985/40287420-d92e8c3c-5cca-11e8-9c00-5b7bd803cb16.PNG)


**But new errors have come up for the same Program as above**

runfile('C:/Users/xyz/Documents/scripts/untitled17.py', wdir='C:/Users/xyz/Documents/scripts')
Traceback (most recent call last):

  File "<ipython-input-2-f6d2d06feac6>", line 1, in <module>
    runfile('C:/Users/xyz/Documents/scripts/untitled17.py', wdir='C:/Users/xyz/Documents/scripts')

  File "C:\Users\xyz\Miniconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\xyz\Miniconda2\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/xyzxyz/Documents/scripts/untitled17.py", line 3, in <module>
    spell = SpellChecker()

  File "C:\Users\xyz\Miniconda2\lib\site-packages\spellchecker\spellchecker.py", line 36, in __init__
    self._word_frequency.load_dictionary(full_filename)

  File "C:\Users\xyz\Miniconda2\lib\site-packages\spellchecker\spellchecker.py", line 211, in load_dictionary
    with gzip.open(filename, 'rt') as fobj:

  File "C:\Users\xyz\Miniconda2\lib\gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)

  File "C:\Users\xyz\Miniconda2\lib\gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')

ValueError: Invalid mode ('rtb')

**Comment by barrust** [comment]
Which version of python are you using? 2.7 or 3?

**Comment by PradeepOjha** [comment]
I was using 2.7 when I reported the two errors. Now I have switched to version 3 and it is working fine. Thanks.

**Comment by barrust** [comment]
Interesting; I thought it could be 2.7. I will do some further tests of of 2.7 but it may be time to retire 2.7 support from the project.
